version: '3.8'

services:
  api:
    container_name: api_container
    build: ./backend
    restart: always
    # env_file:
    #   - "./backend/.env"
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true

  webapp:
    container_name: webapp_container
    restart: always
    build: ./frontend
    ports:
      - 8081:8081
    depends_on:
      - api

  db:
    container_name: db_container
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=root
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
